name: cat_trivia
description: A one and only cat trivia app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cat_fact_client:
    path: ./packages/cat_fact_client
  cat_fact_repository:
    path: ./packages/cat_fact_repository
  cat_image_client:
    path: ./packages/cat_image_client
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.6.2
  retrofit: ^4.0.1
  retrofit_generator: ^6.0.0+3

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
