name: cat_fact_client
description: A dart package to connect to cat fact domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  retrofit: ^4.0.1
  retrofit_generator: ^6.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
